#!/usr/bin/env python3
"""Emit src/app/sitemap.ts from canonical accessors (#1387).

Authorship moved from Phase A (state-11-core-scaffold) to state-11c post-fan-out
so dynamic-segment fixture slugs declared in experiment.yaml's
behaviors[*].dynamic_segments can be enumerated into the sitemap. Phase A
runs BEFORE fixture data exists; only state-11c has the full picture.

Consumes:
  - derive_scope_pages(experiment)         — static page slugs (sorted set)
  - dynamic_public_pages(experiment, repo) — concrete URL instances for
                                              dynamic-segment routes
                                              (e.g., /portfolio/<slug>)

Writes: src/app/sitemap.ts

Convention: URL field follows Next.js MetadataRoute.Sitemap shape. Base URL
derives from process.env.NEXT_PUBLIC_SITE_URL when set (production), else a
relative path (development). The generated file is deterministic given the
same experiment.yaml — re-running this script with no input changes yields
byte-identical output.

CLI:
    python3 .claude/scripts/lib/emit-sitemap.py [--experiment PATH]
                                                  [--out PATH]
                                                  [--repo-root PATH]
"""
from __future__ import annotations

import argparse
import os
import sys
from typing import Any

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from derive_pages import derive_scope_pages, dynamic_public_pages  # type: ignore


_SITEMAP_TEMPLATE = '''import type {{ MetadataRoute }} from 'next';

// Auto-generated by .claude/scripts/lib/emit-sitemap.py during bootstrap
// state-11c post-fan-out (#1387). DO NOT EDIT BY HAND — re-run the script
// after changing experiment.yaml behaviors or dynamic_segments.

function base() {{
  return process.env.NEXT_PUBLIC_SITE_URL ?? '';
}}

export default function sitemap(): MetadataRoute.Sitemap {{
  const now = new Date();
  const b = base();
  return [
{entries}
  ];
}}
'''


def _entry(path: str, priority: float) -> str:
    return (
        f"    {{ url: `${{b}}{path}`, lastModified: now, "
        f"changeFrequency: 'weekly', priority: {priority:.1f} }},"
    )


def emit(experiment: dict[str, Any], repo_root: str = ".") -> str:
    """Render src/app/sitemap.ts contents as a string."""
    entries: list[str] = []

    # Landing root — always present.
    entries.append(_entry("/", 1.0))

    # Static scope pages (excludes landing — already added above).
    scope = derive_scope_pages(experiment)
    for page in scope:
        entries.append(_entry(f"/{page}", 0.7))

    # Dynamic-segment URL instances (#1387 dynamic_public_pages).
    # When repo_root has no src/app/ tree (e.g., test fixture), entries may
    # carry route_pattern=None / concrete_url=None — skip those.
    dyn = dynamic_public_pages(experiment, repo_root)
    for entry in dyn:
        url = entry.get("concrete_url")
        if not url:
            continue
        entries.append(_entry(url, 0.6))

    return _SITEMAP_TEMPLATE.format(entries="\n".join(entries))


def _load_experiment(path: str) -> dict[str, Any]:
    try:
        import yaml  # type: ignore
    except ImportError:
        sys.stderr.write("ERROR: PyYAML not installed (pip install pyyaml)\n")
        sys.exit(2)
    if not os.path.isfile(path):
        sys.stderr.write(f"ERROR: experiment.yaml not found at {path}\n")
        sys.exit(2)
    with open(path, encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Emit src/app/sitemap.ts from canonical page accessors (#1387)."
    )
    parser.add_argument(
        "--experiment",
        default="experiment/experiment.yaml",
        help="Path to experiment.yaml (default: experiment/experiment.yaml).",
    )
    parser.add_argument(
        "--out",
        default="src/app/sitemap.ts",
        help="Output file (default: src/app/sitemap.ts).",
    )
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Project root for dynamic_public_pages filesystem scan (default: cwd).",
    )
    parser.add_argument(
        "--print",
        action="store_true",
        help="Print to stdout instead of writing to disk.",
    )
    args = parser.parse_args()

    experiment = _load_experiment(args.experiment)
    contents = emit(experiment, args.repo_root)

    if args.print:
        sys.stdout.write(contents)
        return 0

    out_dir = os.path.dirname(args.out)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(contents)
    print(f"emit-sitemap: wrote {args.out} ({contents.count('url:')} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
